required = ["github.com/mna/pigeon", "github.com/goreleaser/goreleaser"]

[[constraint]]
  version = "0.2.0"
  name = "github.com/google/go-cmp"

[[override]]
  branch = "master"
  name = "github.com/mna/pigeon"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.10.0"

# Prometheus are currently pre v1.0, so the API is changing considerably.
# The latest release (0.8) predates exported API requirements.
[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "661e31bf844dfca9aeba15f27ea8aa0d485ad212"
